### ISSUE TITLE
max columns progress

### ISSUE THREAD

**Issue by Lijiaoa** [lacolaco/contributors-img#1110]
I think `max columns` is an interesting and useful function! Why not support it? I also say that in issue https://github.com/lacolaco/contributors-img/issues/18

**Comment by lacolaco** [comment]
@Lijiaoa Thank you for the feedback! Currently, the column count is 12. I'd like to make it customizable.
How many columns are needed for your usecase?

**Comment by lacolaco** [comment]
`columns={number}` parameter is now supported. 👍
