### ISSUE TITLE
Exclude bots from image?

### ISSUE THREAD

**Issue by brian-rose** [lacolaco/contributors-img#1175]
Hi @lacolaco, really neat app!

Is there a way to exclude bots (e.g. dependabot) from the contributors image?

**Comment by lacolaco** [comment]
@brian-rose Thank you for your feedback. Currently, it is not possible. 
I think it is difficult to identify which user is a bot, but it is possible to add a heuristic (e.g. banned list) logic to exclude bots.

**Comment by samuelfernandez** [comment]
This would be great! Some that should be excluded:

* semantic-release-bot
* renovate-bot

**Comment by lacolaco** [comment]
@brian-rose 
I'll publish a fixed version into production soon! Please see #1262 if you are interested in the details of the fix.  

cc/ @samuelfernandez

**Comment by lacolaco** [comment]
Generated images are strongly cached for one day. This fix may be applied to the image from tomorrow.
