### ISSUE TITLE
BUG - not showing contributor avatar's for some repos

### ISSUE THREAD

**Issue by yashash1511** [lacolaco/contributors-img#1271]
![image](https://user-images.githubusercontent.com/89068816/184546414-81a547f5-02de-4658-94c3-7379d8efa8a5.png)

https://contrib.rocks/image?repo=blueedgetechno/win11React

**Comment by yashash1511** [comment]
nvm it works fine now

**Comment by suzuki-shunsuke** [comment]
I'm facing a same error.

https://contrib.rocks/preview?repo=aquaproj%2Faqua-registry

<img width="990" alt="image" src="https://user-images.githubusercontent.com/13323303/217192678-37e01c5c-76cd-4a70-9533-c8374bf10fbe.png">

**Comment by suzuki-shunsuke** [comment]
This issue was closed, so I'll create a new issue.
