### ISSUE TITLE
Add an option to exclude anonymous users

### ISSUE THREAD

**Issue by Tsuk1ko** [lacolaco/contributors-img#1295]
After #1264, I found my contributors image contain a lot of anonymous avatars.

I used to use some custom email addresses to commit in GitHub Actions. I don't need them to display in the image, because it will look ugly.

Could you consider adding this option?

Thanks for your work, this app is great!

**Comment by lacolaco** [comment]
@Tsuk1ko Thank you for the feedback! In a few weeks, I'll add an option like `anon=1` to toggle the behavior.

**Comment by lacolaco** [comment]
@Tsuk1ko `anon` option is out! Including anonymous users is now an opt-in feature. They are not included by default.
