### ISSUE TITLE
How to set higher-definition pictures ?

### ISSUE THREAD

**Issue by warmthsea** [lacolaco/contributors-img#1490]

**Comment by LIGMATV** [comment]
You can use [contib.nn.ci](https://contrib.nn.ci/), which is so customizable. You can see they're [configuration](https://github.com/xhofe/gh-contributors?tab=readme-ov-file#usage).

**Comment by warmthsea** [comment]
> You can use [contib.nn.ci](https://contrib.nn.ci/), which is so customizable. You can see they're [configuration](https://github.com/xhofe/gh-contributors?tab=readme-ov-file#usage).

Thanks.
